FROM debian:9
LABEL maintainer="Snowind <jinks.tao@gmail.com>" \
      description="vsftpd docker image based on debian 9" \
      usage="sudo docker run -d -p 20:20 -p 21:21 -p 30000-30100:30000-30100 \
            -v /home/vsftpd:/home/vsftpd \
            -e PASV_ADDRESS=127.0.0.1 \
            -e PASV_MIN_PORT=30000 -e PASV_MAX_PORT=30100 \
            -e ANONYMOUS_ENABLE=NO -e LOCAL_ENABLE=YES -e WRITE_ENABLE=YES \
            -e LOCAL_UMASK=022 -e DIRMESSAGE_ENABLE=YES -e USE_LOCALTIME=YES\
            -e connect_from_port_20=YES -e CHROOT_LOCAL_USER=YES \
            --name vsftpd --restart=always --cap-add SYS_ADMIN \
            snowind/vsftpd:latest" \
      version="0.8"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install vsftpd -y && \
    apt-get clean && \
    update-rc.d -f vsftpd remove && \
    mkdir -p /home/vsftpd

ENV ALLOW_ANON_SSL NO
ENV ANON_MKDIR_WRITE_ENABLE NO
ENV ANON_OTHER_WRITE_ENABLE NO
ENV ANON_UPLOAD_ENABLE NO
ENV ANON_WORLD_READABLE_ONLY YES
ENV ANONYMOUS_ENABLE YES
ENV ASCII_DOWNLOAD_ENABLE NO
ENV ASCII_UPLOAD_ENABLE NO
ENV ASYNC_ABOR_ENABLE NO
ENV BACKGROUND NO
ENV CHECK_SHELL YES
ENV CHMOD_ENABLE YES
ENV CHOWN_UPLOADS NO
ENV CHROOT_LIST_ENABLE NO
ENV CHROOT_LOCAL_USER NO
ENV CONNECT_FROM_PORT_20 NO
ENV DEBUG_SSL NO
ENV DELETE_FAILED_UPLOADS NO
ENV DENY_EMAIL_ENABLE NO
ENV DIRLIST_ENABLE YES
ENV DIRMESSAGE_ENABLE NO 
ENV DOWNLOAD_ENABLE YES
ENV DUAL_LOG_ENABLE NO
ENV FORCE_DOT_FILES NO
ENV FORCE_ANON_DATA_SSL NO
ENV FORCE_ANON_LOGINS_SSL NO
ENV FORCE_LOCAL_DATA_SSL YES
ENV FORCE_LOCAL_LOGINS_SSL YES
ENV GUEST_ENABLE NO
ENV HIDE_IDS NO
ENV IMPLICIT_SSL NO
ENV LISTEN YES
ENV LISTEN_IPV6 NO
ENV LOCAL_ENABLE NO
ENV LOCK_UPLOAD_FILES YES
ENV LOG_FTP_PROTOCOL NO
ENV LS_RECURSE_ENABLE NO
ENV MDTM_WRITE YES
ENV NO_ANON_PASSWORD NO
ENV NO_LOG_LOCK NO
ENV ONE_PROCESS_MODEL NO
ENV PASSWD_CHROOT_ENABLE NO
ENV PASV_ADDR_RESOLVE NO
ENV PASV_ENABLE YES
ENV PASV_PROMISCUOUS NO
ENV PORT_ENABLE YES
ENV PORT_PROMISCUOUS NO
ENV REQUIRE_CERT NO
ENV REQUIRE_SSL_REUSE YES
ENV RUN_AS_LAUNCHING_USER NO
ENV SECURE_EMAIL_LIST_ENABLE NO
ENV SESSION_SUPPORT NO
ENV SETPROCTITLE_ENABLE NO
ENV SSL_ENABLE NO
ENV ssl_request_cert YES
ENV SSL_SSLV2 NO
ENV SSL_SSLV3 NO
ENV SSL_TLSV1 YES
ENV STRICT_SSL_READ_EOF NO
ENV STRICT_SSL_WRITE_SHUTDOWN NO
ENV SYSLOG_ENABLE NO
ENV TCP_WRAPPERS NO
ENV TEXT_USERDB_NAMES NO
ENV TILDE_USER_ENABLE NO
ENV USE_LOCALTIME NO
ENV USE_SENDFILE YES
ENV USERLIST_DENY YES
ENV USERLIST_ENABLE NO
ENV VALIDATE_CERT NO
ENV VIRTUAL_USE_LOCAL_PRIVS NO
ENV WRITE_ENABLE NO
ENV XFERLOG_ENABLE NO
ENV XFERLOG_STD_FORMAT NO
ENV ACCEPT_TIMEOUT 60
ENV ANON_MAX_RATE 0
ENV ANON_UMASK 077
ENV CHOWN_UPLOAD_MODE 0600
ENV CONNECT_TIMEOUT 60
ENV DATA_CONNECTION_TIMEOUT 300
ENV DELAY_FAILED_LOGIN 1
ENV DELAY_SUCCESSFUL_LOGIN 0
ENV FILE_OPEN_MODE 0666
ENV FTP_DATA_PORT 20
ENV IDLE_SESSION_TIMEOUT 300
ENV LISTEN_PORT 21
ENV LOCAL_MAX_RATE 0
ENV LOCAL_UMASK 077
ENV MAX_CLIENTS 0
ENV MAX_LOGIN_FAILS 3
ENV MAX_PER_IP 0
ENV PASV_MAX_PORT 0
ENV PASV_MIN_PORT 0
ENV TRANS_CHUNK_SIZE 0
ENV ANON_ROOT ''
ENV BANNED_EMAIL_FILE /etc/vsftpd.banned_emails
ENV BANNER_FILE ''
ENV CA_CERTS_FILE ''
ENV CHOWN_USERNAME root
ENV CHROOT_LIST_FILE /etc/vsftpd.chroot_list
ENV CMDS_ALLOWED ''
ENV CMDS_DENIED ''
ENV DENY_FILE ''
ENV DSA_CERT_FILE ''
ENV DSA_PRIVATE_KEY_FILE ''
ENV EMAIL_PASSWORD_FILE /etc/vsftpd.email_passwords
ENV FTP_USERNAME ftp
ENV FTPD_BANNER ''
ENV GUEST_USERNAME ftp
ENV HIDE_FILE ''
ENV LISTEN_ADDRESS ''
ENV LISTEN_ADDRESS6 ''
ENV LOCAL_ROOT ''
ENV MESSAGE_FILE .message
ENV NOPRIV_USER nobody
ENV PAM_SERVICE_NAME ftp
ENV PASV_ADDRESS ''
ENV RSA_CERT_FILE /usr/share/ssl/certs/vsftpd.pem
ENV RSA_PRIVATE_KEY_FILE ''
ENV SECURE_CHROOT_DIR /usr/share/empty
ENV SSL_CIPHERS DES-CBC3-SHA
ENV USER_CONFIG_DIR ''
ENV USER_SUB_TOKEN ''
ENV USERLIST_FILE /etc/vsftpd.user_list
ENV VSFTPD_LOG_FILE /var/log/vsftpd.log
ENV XFERLOG_FILE /var/log/xferlog

COPY vsftpd /etc/pam.d/
COPY ftpusers /etc/
COPY init.sh /usr/sbin/

RUN chmod +x /usr/sbin/init.sh

VOLUME /home/vsftpd

EXPOSE 20 21

CMD ["/usr/sbin/init.sh"]
